new yaml renv

diff --git a/.github/workflows/r-scripts-workflow.yml b/.github/workflows/r-scripts-workflow.yml
--- a/.github/workflows/r-scripts-workflow.yml
+++ b/.github/workflows/r-scripts-workflow.yml
@@ -1,4 +1,4 @@
-name: jobber_ME01_gme_offerte
+name: jobber_ME01_gme
 
 on:
   push:
@@ -15,29 +15,36 @@ jobs:
     - name: Checkout repository
       uses: actions/checkout@v2
 
-    - name: Set up R
+    - name: Set up R and renv
       uses: r-lib/actions/setup-r@v2
-      with:
-        use-public-rspm: true
-
+      
     - name: Install system dependencies
       run: |
         sudo apt-get update
-        sudo apt-get install -y libssl-dev libsasl2-dev jq libpq-dev libcurl4-openssl-dev
+        sudo apt-get install -y libssl-dev libsasl2-dev jq libpq-dev libcurl4-openssl-dev pkg-config
+        sudo apt-get install -y libxml2-dev libgit2-dev
+        sudo apt-get install --reinstall -y curl
+        echo "Checking libcurl version..."
+        curl-config --version || echo "libcurl is missing"
+        echo "Checking curl.h path..."
+        find /usr -name curl.h 2>/dev/null      
+      
+    - name: Uses renv
+      uses: r-lib/actions/setup-renv@v2      
+
+    - name: Install `fluxer` package from GitHub
+      env:
+        GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
+      run: |
+        Rscript -e "install.packages('remotes')"
+        Rscript -e "install.packages('curl')"
+        Rscript -e "Sys.setenv(GITHUB_PAT = '${{ secrets.PAT_GITHUB }}')"
+        Rscript -e "remotes::install_github('mbsenergy/fluxer')"
 
     - name: Install dependencies with renv
       run: |
         Rscript -e "install.packages('renv')"
         Rscript -e "renv::restore()"
-
-    - name: Set up Git credentials for private repo access
-      run: |
-        git config --global url."https://${{ secrets.PAT_GITHUB }}@github.com/".insteadOf "https://github.com/"
-
-    - name: Install `fluxer` package from GitHub
-      run: |
-        Rscript -e "install.packages('remotes')"
-        Rscript -e "remotes::install_github('mbsenergy/fluxer', auth_token = '${{ secrets.PAT_GITHUB }}')"
 
     - name: Run Jobber full script
       env:
@@ -47,4 +54,4 @@ jobs:
         PG_FLUX_USER: ${{ secrets.PG_FLUX_USER }}
         PG_FLUX_PSW: ${{ secrets.PG_FLUX_PSW }}
       run: |
-        Rscript -e 'source("RScripts/00_jobber.R")'
+        Rscript RScripts/00_jobber.R
